# SPDX-License-Identifier: MPL-2.0
# Optional, separate database release; see appco-postgresql.lock.json and README.
# This is a rendered candidate, not a tested database migration or HA claim.
# Required existing namespace Secrets: application-collection, lolly-postgres-auth,
# and lolly-postgres-tls. Review storageClassName and resource sizes for your host.
global:
  imagePullSecrets:
    - application-collection

images:
  postgresql:
    registry: dp.apps.rancher.io
    repository: containers/postgresql
    tag: "17.11-22.3"
    digest: "sha256:86d2c922014118dcb965295a344c058916829d4137f33659d6a636032df8073a"

nodeCount: 1
auth:
  database: lollywork
  username: lollywork
  existingSecret: lolly-postgres-auth
  passwordKey: password
  postgresPasswordKey: postgresPassword
  replicationPasswordKey: replicationPassword

tls:
  enabled: true
  existingSecret: lolly-postgres-tls
  certFilename: server.crt
  keyFilename: server.key
  caCertFilename: ca.crt

metrics:
  enabled: false

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 16Gi

podTemplates:
  containers:
    postgresql:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
          ephemeral-storage: 128Mi
        limits:
          cpu: "1"
          memory: 1Gi
          ephemeral-storage: 1Gi
