// SPDX-License-Identifier: MPL-2.0
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { contentHash } from '../scripts/lib/content-hash.ts';

test('engine pins ignore installed workspace binaries but detect source changes', (t) => {
  const root = mkdtempSync(join(tmpdir(), 'lolly-engine-pin-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  writeFileSync(join(root, 'source.ts'), 'export const version = 1;');
  const before = contentHash(root);
  mkdirSync(join(root, 'node_modules/.bin'), { recursive: true });
  writeFileSync(join(root, 'node_modules/.bin/tsc'), 'generated by pnpm');
  assert.equal(contentHash(root), before);
  writeFileSync(join(root, 'source.ts'), 'export const version = 2;');
  assert.notEqual(contentHash(root), before);
});
