// SPDX-License-Identifier: MPL-2.0
/**
 * Write deploy/vm/Caddyfile: Caddy in front of the lolly-work server on one VM
 * (deploy/vm/README.md), generated by `caddyfile()` in scripts/vercel-routes.ts
 * from the same router scan as the Vercel route table.
 *
 *   node scripts/build-caddyfile.ts [--check] [--out <file>]
 *     [--domain lolly.ing] [--redirect www.lolly.ing]... [--shell-origin https://lolly.tools]
 *     [--upstream server:8787]
 *
 * The defaults are lolly.ing's. `--check` writes nothing and exits 1 when the
 * file differs from what would be generated (deploy/vm/push.sh runs it).
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { caddyfile, functionPrefixes, type CaddyOptions } from './vercel-routes.ts';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const CADDYFILE_PATH = join(ROOT, 'deploy', 'vm', 'Caddyfile');

/** lolly.ing on one VM: the compose service `server` behind Caddy, the app from lolly.tools. */
export const LOLLY_ING: Omit<CaddyOptions, 'prefixes'> = {
  domain: 'lolly.ing',
  redirectDomains: ['www.lolly.ing'],
  shellOrigin: 'https://lolly.tools',
  upstream: 'server:8787',
};

export function generate(options: Omit<CaddyOptions, 'prefixes'> = LOLLY_ING): string {
  return caddyfile({ ...options, prefixes: functionPrefixes(join(ROOT, 'server', 'src')) });
}

export function main(argv = process.argv.slice(2)): number {
  const options: Omit<CaddyOptions, 'prefixes'> & { redirectDomains: string[] } = { ...LOLLY_ING, redirectDomains: [] };
  let out = CADDYFILE_PATH;
  let check = false;
  let redirectsGiven = false;
  for (let i = 0; i < argv.length; i++) {
    const flag = argv[i]!;
    const value = (): string => {
      const v = argv[++i];
      if (!v || v.startsWith('--')) throw new Error(`${flag} needs a value`);
      return v;
    };
    if (flag === '--check') check = true;
    else if (flag === '--out') out = resolve(value());
    else if (flag === '--domain') options.domain = value();
    else if (flag === '--redirect') { options.redirectDomains.push(value()); redirectsGiven = true; }
    else if (flag === '--shell-origin') options.shellOrigin = value();
    else if (flag === '--upstream') options.upstream = value();
    else throw new Error(`unknown flag ${flag}`);
  }
  if (!redirectsGiven) options.redirectDomains = [...(LOLLY_ING.redirectDomains ?? [])];
  const text = generate(options);
  if (check) {
    const current = existsSync(out) ? readFileSync(out, 'utf8') : '';
    if (current !== text) {
      console.error(`[build-caddyfile] ${out} is not current. Run node scripts/build-caddyfile.ts and review the change.`);
      return 1;
    }
    console.log(`[build-caddyfile] ${out} is current`);
    return 0;
  }
  writeFileSync(out, text);
  console.log(`[build-caddyfile] wrote ${out}`);
  return 0;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    process.exitCode = main();
  } catch (err) {
    console.error(`[build-caddyfile] ${(err as Error).message}`);
    process.exitCode = 1;
  }
}
